### DISCUSSION TITLE
如何获取语法树节点中嵌套的信息

### DISCUSSION THREAD

**Discussion by SundayDream00** [arcsysu/SYsU-lang#41] [Q&A]
助教好，想询问一些关于获取语法树节点中信息的问题，如下：

1. 如对于基本的变量赋值语句`a=10;`，语法树相关节点如下：
```
id: '0xd77fd8'
      kind: BinaryOperator
      range:
        begin:
          offset: 231
          line: 11
          presumedLine: 4
          col: 5
          tokLen: 1
        end:
          offset: 233
          col: 7
          tokLen: 2
      type:
        qualType: int
      valueCategory: rvalue
      opcode: "="
      inner:
      - id: '0xd77f98'
        kind: DeclRefExpr
        range:
          begin:
            offset: 231
            col: 5
            tokLen: 1
          end:
            offset: 231
            col: 5
            tokLen: 1
        type:
          qualType: int
        valueCategory: lvalue
        referencedDecl:
          id: '0xd77d50'
          kind: VarDecl
          name: a
          type:
            qualType: int
      - id: '0xd77fb8'
        kind: IntegerLiteral
        range:
          begin:
            offset: 233
            col: 7
            tokLen: 2
          end:
            offset: 233
            col: 7
            tokLen: 2
        type:
          qualType: int
        valueCategory: rvalue
        value: '10'
```
为了获取`a_ptr`，需要得到`DeclRefExpr`节点` referencedDecl`里的`name`信息获取变量名，请问这个信息需要用什么API得到呢？或者说是否有其他的简便方法直接得到`a_ptr`呢？

2. 对于数组定义，如语句`int a[10][10];`，语法树中相关节点如下：
```
    {
      "id": "0x1281e48",
      "kind": "VarDecl",
      "loc": {
        "offset": 209,
        "file": "<stdin>",
        "line": 8,
        "presumedFile": "tester/function_test2020/00_arr_defn2.sysu.c",
        "presumedLine": 1,
        "col": 5,
        "tokLen": 1
      },
      "range": {
        "begin": {
          "offset": 205,
          "col": 1,
          "tokLen": 3
        },
        "end": {
          "offset": 217,
          "col": 13,
          "tokLen": 1
        }
      },
      "name": "a",
      "mangledName": "a",
      "type": {
        "qualType": "int [10][10]"
      }
    }
```
a. 请问该如何获取`type`->`qualType`中的数组大小信息呢？
b. 另外，对于语雀中提供的范例数组生成语句
```
llvm::Value* idx = llvm::ConstantInt::get(TheContext, llvm::APInt(32, size));
Builder.CreateInBoundsGEP(arr, {llvm::ConstantInt::get(TheContext, llvm::APInt(32, 0)), idx});
```
其中对于多维数组，如此程序中直接将size传为100，得到如下所示的中间代码1，是正确的吗？
```
// 中间代码1
%a = alloca [100 x i32], align 4

// 标准代码
%a = alloca [10 x [10 x i32]], align 16
```
